### ISSUE TITLE
Dashes, en-dash and em-dash guidance

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#104]
# Issue

Users are reporting confusion around seeing un-spaced em-dashes (over dashes or en-dashes spaced or un-spaced).

We currently recommend using un-spaced em-dashes in headings and body (for example&mdash;like this).

## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/h.html#hyphens-and-dashes

## Good example

https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#dates

**Comment by michaelhugill** [comment]
Hi @joolswood, just wanting to confirm if the change to adding spaces around an em-dash will actually take place, or if it's just going to committee for discussion? Thanks.

**Comment by joolswood** [comment]
Hi @michaelhugill I've added this for discussion at content clinic today. Cheers

**Comment by joolswood** [comment]
Action to check on screen reader support for space em-dash space.
Support for using `to` over en-dash for ranges.

**Comment by joolswood** [comment]
Andrew Arch reported, based on another user's experience with screen reader:

```
feedback o/night from a JAWS user is that the emdash is ignored in normal reading (with /without space), but the spaces help if reading a word at a time. This was based on putting an emdash in email the two different ways.
```

Based on this I suggest we move to space em dash space.

I do have some reservation that the width of space em dash space may prove too large. We may need to revise this at some point in the future (possibly move to space hyphen space).

**Comment by joolswood** [comment]
I’ve not used ‘from’ in the examples. Happy to revisit this.

**Comment by joolswood** [comment]
https://github.com/AusDTO/gov-au-content-guide/commit/732d44db9e9d9553c81a65fca4256db9d88758fd
