### ISSUE TITLE
Gerund use in headings

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#106]
## What do you need?

I've been having some discussions about present tense vs present continuous (gerund) for page names and sub headings. It's coming up a lot in topic (e.g ‘set up’ vs ‘setting up’ or ‘providing...’):

I know present tense is preferenced in the style guide but it only makes sense to me (as a page name or subheading) for transactional content where a user can complete a task (e.g. 'apply for a visa'). The gerund seems more appropriate for guidance.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/v.html#voice

**Comment by joolswood** [comment]
Action: add title example to voice entry.

**Comment by michellemortimer** [comment]
Draft only:

"Make headings and page titles active when users can complete a task, for example submitting an application form. Think of it as a call to action.

For example:
'Enrol to vote'
'Apply for a licence'

Use the gerund (-ing verbs) in headings when the content provides guidance but the user can’t take a direct action.

For example:
'Caring for someone'
'Protecting your identity online'"

**Comment by michellemortimer** [comment]
Maybe this guidance is more appropriate under 'headings' or 'titles', similar to GOV.UK: https://www.gov.uk/guidance/content-design/writing-for-gov-uk

**Comment by joolswood** [comment]
Thanks @michellemortimer just having a chat with @maadonna on this. Maybe we should apply this more to subheadings than titles? There's probably fewer verbs that also work well as good keywords; `Enrol to vote` might be one.

**Comment by michellemortimer** [comment]
No worries @joolswood. We're actually talking about this right now - @michaelhugill @matthewmccarthyDTO and I are working on a page called 'Immunising your child'. It would seem odd to call the page 'Immunise your child' - sounds like an imperative/command?

I'm not 100% sure on the grammar rules...on reflection, I don't think this is technically a gerund - maybe just present continuous tense? Maybe we need to discuss more in person.

**Comment by maadonna** [comment]
Often you can flip them to noun forms instead of verbs/gerunds - this could be 'Childhood immunisation'. In the past I've usually tried to make them all (much shorter) noun forms then only used verb/gerunds if the noun form makes little sense. I'm talking about page titles only though, and only in situations where the page is general information, not tasks :)

**Comment by nigelbartlett** [comment]
True, but 'Childhood immunisation' could be very broad. It could mean (for
instance) the whole range of government policy surrounding child
immunisation. What 'Immunising your child' refers to is more specific.

N.

*Nigel Bartlett*
Content designer
Digital Transformation Office
www.DTO.gov.au <http://www.dto.gov.au/>

**Comment by maadonna** [comment]
Of course. That's why I always try the noun form and see if it still has the same meaning :)

**Comment by joolswood** [comment]
I've added some [draft content on this](https://github.com/AusDTO/gov-au-content-guide/commit/af1078ff5c11c16215f1ef7080e552bf5d533320).

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/24
