### ISSUE TITLE
State/territory order in lists

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#108]
## What do you need?

User has suggested we recommend that lists of states/territories are ordered from largest to smallest (assume by population). The ABS does this.

We currently have an alphabetical order example.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/g.html#government-naming-conventions
## Good example

http://www.abs.gov.au/ausstats/abs@.nsf/0/BCDDE4F49C8A3D1ECA257B8F00126F77?Opendocument

**Comment by maadonna** [comment]
Some rationale for this one... Putting them in this order means the 'biggest' (which also will usually represent the highest user need) is at the front of a list, and the smallest toward the end. It's also really good when representing tabular, numeric data, as the data is much easier to read when there is some order to it.

Alphabetical is not really a good order in this case. ACT ends up at the front, though is usually the least important item in the list.

We most definitely should make a rule/guideline for this or every author will do it in a different way :)

**Comment by joolswood** [comment]
Thanks @maadonna for adding the background on this.

**Comment by maadonna** [comment]
I just realised that the ABS list is not quite logical. They have SA then WA, but the populations are the opposite. I think we should go with logic, not their way...

**Comment by AndrewArch** [comment]
can we test for a person's current location and put that at the top (on the assumption that mostly it would be what they need)?

**Comment by maadonna** [comment]
That's a good idea & will be possible in some situations, but we'll still have lists of states in content that never need to be adaptive & still need a rule

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/30
