### ISSUE TITLE
Page summaries pattern

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#109]
## What do you need?

A pattern for how to write common introductory material for pages (for example what goes in the first sentence, then first para).

@michael.hugill if you'd like to add any more detail here, please do.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/writing-for-the-web/ ?

**Comment by michaelhugill** [comment]
Hi @joolswood, do you happen to have a deadline for this one?

**Comment by joolswood** [comment]
@michaelhugill Libby marked it as "phase 2", not sure what that means in terms of timing. If there's a need to speed things up we can.

**Comment by klepas** [comment]
@joolswood Sounds like this would inform the article/main header content and it’s markup and styling requirements. If anything pertains to us let me know :)

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/70
