### ISSUE TITLE
File size, download time & reading time

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#110]
## What do you need?

A couple of users have raised intersecting suggestions relating to linking to files:
1. Provide an estimated download time based on average connection speed.
2. Provide estimated reading time for text file.

I think we should also investigate where we discuss listing file size in the guide. At the moment it is only in PDFs I think.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/p.html#pdfs

**Comment by joolswood** [comment]
We should investigate the user need for these. My gut feeling is that number 1 would cause more (content and technical) problems than it would solve, however.

**Comment by maadonna** [comment]
My *opinion* on this is that if people can't figure out what 'big' looks like (e.g. is 5MB a big file or is 5GB a big file) they are also unlikely to know what kind of connection speed they have.

What is 'average' connection speed anyway.

I think one of the game platforms does this (downloads in 30mins at nnnn speed). I'm always like 'cool, 30 minutes' and then I start to download and find out it is going to take all night. Not a good experience...

**Comment by klepas** [comment]
> Provide estimated reading time for text file.

This can be done in dynamic templates, eg get the # of words for a section of content you want to give an estimate for, and then divide by 160–180, and give in minutes. (:

We can do this really easily in Jekyll btw (:

Related reference: https://en.wikipedia.org/wiki/Words_per_minute#Reading_and_comprehension

**Comment by joolswood** [comment]
Content clinic discussed this. We will return to it when we can.

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/71
