### ISSUE TITLE
Is the word Anzac meant to be capital letters?

### ISSUE THREAD

**Issue by LausKovu** [AusDTO/gov-au-content-guide#111]
Is the word Anzac meant to be capital letters?

How is Anzac written as the acronym for Australian and New Zealand Army Corps: is it ANZAC or Anzac? what is the Australian Government position?

The A to Z currently shows it somewhere as Anzac.

## Which entry/section is this related to?
A to Z of the guide, could go in either:
Abbreviations and Acronyms 
Government naming conventions.

## Good example
Page 10 of the http://rslsa.org.au/Media/Default/ANZAC%20Day/2016%20Anzac%20Day%20Media%20Style%20Guide%20-%20Centenary%20Edition.pdf says: 

"In 1921, a law was passed in Australia to protect ‘Anzac’ as a word. The Protection of Word ‘Anzac’ Regulations refer to both ANZAC and Anzac, using upper and lower case letters. Similar Acts have been passed in New Zealand and the United Kingdom." 

Another source is: www.anzaccentenary.gov.au/about-anzac-centenary/use-word-anzac

The Style Manual says at page 129 under the heading 'Holidays, religious days and public events'
"Anzac Day" and follows with "Note that although Anzac is an acronym for 'Australian and New Zealand Army Corps' and thus might be given full capitals, it falls into the category of familiar acronyms that take only an initial capital (see page 153). This usage is enshrined in The Protection of the Word 'Anzac' Regulations, administered by the Minister for Veterans' Affairs."

**Comment by joolswood** [comment]
Suggestion - the style guide has a reference to Anzac which needs an additional sentence. 'Most acronyms for companies or organisations are uppercase with the exception of Anzac.' It should state that if you are referencing the actual army formation then it is upper case ANZAC.

**Comment by joolswood** [comment]
Content Clinic agrees to leave as is.
