### ISSUE TITLE
PDF entry layout

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#113]
## What do you need?

Andrew suggested the PDF entry may be better displayed as an image showing the pattern for placing one into a page/screen. See how GDS shows how to put a pdf on a page with: thumbnail image, title, description, pdf icon, file size. 
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/p.html#pdfs
## Good example

https://www.gov.uk/government/uploads/system/uploads/attachment_data/file/361677/corporate-report-good-example.pdf 
https://www.gov.uk/guidance/how-to-publish-on-gov-uk/accessible-pdfs

**Comment by klepas** [comment]
This sounds like something @maadonna might be interested in too, given that this could become a little pattern in the UI KIt and is available for template implementers to use for their authors when adding PDFs to things.

The tech specifics on the dynamic templating are nuanced… but the styling for this as a pattern is definitely something we could standardise in the UI-Kit.

**Comment by AndrewArch** [comment]
@klepas - happy to workshop this with you and others when appropriate

**Comment by klepas** [comment]
I suspect this will be put on the backburner as a pattern. We have it tracked here, so it’s in our backlog. (:

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/69
