### ISSUE TITLE
Last updated/reviewed

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#114]
## What do you need?

As a user I want to know how current the info on a page is by seeing 'last reviewed' for example.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/writing-for-the-web/4-pre-writing-checklist.html

**Comment by klepas** [comment]
Just a quick note that a technical fix for this is feasible, eg usingu Jekyll to insert a timestamp when a piece of content was last updated.

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/68
