### ISSUE TITLE
Faces in photos

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#116]
## What do you need?

Last one from Andrew Arch:

Put advice for when including an image of a person in a page, that the person's eyes in the image should look towards the content around the image and not away from that content. Why? People's eyes follow the gaze away from the content.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/i.html#images

**Comment by joolswood** [comment]
@AndrewArch to draft text

**Comment by klepas** [comment]
@AndrewArch I think this is sitting with you? :)

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/39
