### ISSUE TITLE
The pattern in the A to Z which show 'For example'

### ISSUE THREAD

**Issue by LausKovu** [AusDTO/gov-au-content-guide#117]
## What do you need?

As a user I want to see clearly that I am been shown a **For example** throughout the A to Z and Writing for the Web. 
## What is the problem?

At present a full review of the pattern that is applied to **For example** is yet to be undertaken. I also note that the ways some **For example** are shown is not as clear and easy to understand for a user as it could be.
## Which entry/section is this related to?

In the A to Z, I have noted many weeks ago now the following (may or may not be still the same):
- For all the entries throughout: 

do we use a full stop before showing a **For example** ?

we've been using the wording 'Like this', 'Not like this', 'Or like this', 'But not like this' can we improve on this usage within the pattern? See the entry for Commas as an example: http://content-style-guide.apps.staging.digital.gov.au/az-indexes/c.html#commas
- At Video http://content-style-guide.apps.staging.digital.gov.au/az-indexes/v.html#video
  under the subheading 'Accessibility' the bullet points don't show the dashes correctly.
- At Titles http://content-style-guide.apps.staging.digital.gov.au/az-indexes/t.html#titles in the second **For example** don't show the dash correctly.
- At Time http://content-style-guide.apps.staging.digital.gov.au/az-indexes/t.html#time question the guidance of: "Use a colon for the 24-hour clock." Also do we put guidance in for how to write "24 hr" ?
- At Apostrophe http://content-style-guide.apps.staging.digital.gov.au/az-indexes/a.html#apostrophe the copy is in H3 as follows:
  
  <h3 id="indicates-possession">Indicates possession</h3>
  
  <h3 id="is-used-for-expressions-of-time">Is used for expressions of time</h3>
  
  <h3 id="dont-use-for-plural-abbreviation">Don’t use for plural abbreviation</h3>
  
  <h3 id="dont-use-for-decades">Don’t use for decades</h3>
  
  <h3>Please also see</h3>
- At Audience http://content-style-guide.apps.staging.digital.gov.au/az-indexes/a.html#audience the bullet points show em or en dashes with no spaces either side.
- At Inclusivity & diversity http://content-style-guide.apps.staging.digital.gov.au/az-indexes/i.html#inclusivity-diversity there's em or en dashes with no spaces either side.
- At Navigation labels http://content-style-guide.apps.staging.digital.gov.au/az-indexes/n.html#navigation-labels remove the apostrophe from "page’s title" it should be "page title"
- At A to Z http://content-style-guide.apps.staging.digital.gov.au/az-guide.html under the 'What is this?' the words "that is precise and specific" seem odd. Isn't specific a synonym of precise? Suggestion: delete 'precise' in favour of just using the plainer english 'specific'.
- At Dictionaries and Spell checkers http://content-style-guide.apps.staging.digital.gov.au/az-indexes/d.html#dictionaries-spell-checkers the words "more similar" don't read / sound right.
- At Documents http://content-style-guide.apps.staging.digital.gov.au/az-indexes/d.html#documents "Microsoft Word format" is not an accurate word choice, because the format is a ".doc" the program application as in https://products.office.com/en-au/word is 'Microsoft Word'. Also, "viewed on a mobile" is maybe not an accurate word choice as "on a mobile" does not tell the reader if the issue is the mobile device or the mobile device screen size. Suggestion: better read, if said like this: "The Microsoft Word file format .doc does not currently conform to WCAG 2.0 when viewed on some mobile device screens.
- At SEO & metadata http://content-style-guide.apps.staging.digital.gov.au/az-indexes/s.html#seo-and-metadata there is no content here. A link still needs to go from the entry to the 'Writing for the web page' on 'Optimise your content for search'.
- At Fact sheets http://content-style-guide.apps.staging.digital.gov.au/az-indexes/f.html#fact-sheets consider front loading the following sentence so it is easier to read: "Fact sheet information should first be offered as an accessible and printable HTML page." flip it so it reads: "Fact sheet  information should appear first as HTML on a web page to meet accessibility requirements and allow for printing."
## Good example

No examples to show.

**Comment by joolswood** [comment]
Will review to check what has been done.
