### ISSUE TITLE
Program vs programme

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#119]
## What do you need?

Clear guidance on program vs programme.

There's been a lot of traffic in the Google Group on this issue recently. Let's try and tie it off at content clinic this morning.

## Which entry/section is this related to?

As a starting place there's a draft new entry here: https://github.com/AusDTO/gov-au-content-guide/blob/bugfix/content-clinic/_entries/2016-05-04-program.md

And a new draft of the government wording and capitalisation here: https://github.com/AusDTO/gov-au-content-guide/blob/bugfix/content-clinic/_entries/2016-05-04-government-naming-conventions.md

## Good example

https://www.macquariedictionary.com.au/news/view/editor/article/17/

**Comment by joolswood** [comment]
Group agreed to draft entry as stands. Lisa H to action other supporting content.

**Comment by lhowdin** [comment]
I think the advice is "Use program in all cases, except where a program is named in legislation with 'programme'.     More detailed advice, and for more discussion in a clinic perhaps: "Avoid using program names and refer to to service they provide/the task people need to complete." The exception to this is within the corporate section.

**Comment by joolswood** [comment]
After discussion @lhowdin agreed to leave new entry as is for now.
