### ISSUE TITLE
Remove period / full stop from the end of lists in guidance

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#121]
## What do you need?

User has suggested advising removing the full stop from the ends of lists to reduce visual clutter.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/b.html#bullet-point-lists
## Good example

https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#bullet-points-steps

**Comment by joolswood** [comment]
Assigned to Matthew to find examples

**Comment by libbyv** [comment]
AA says it won't make any diff either way for a screen reader.

**Comment by joolswood** [comment]
#211 relates

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/23
