### ISSUE TITLE
Contractions usage

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#123]
## What do you need?

User needs more guidance on when to use contractions. Requested by @matthewmccarthy
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/c.html#contractions
## Good example

https://www.gov.uk/guidance/content-design/writing-for-gov-uk#contractions

**Comment by joolswood** [comment]
Section needs improvement.

**Comment by michaelhugill** [comment]
@libbyv New suggestion below as requested on Slack (cc @joolswood).

Use contractions carefully to make your voice and tone more conversational. Remember that low-literacy users and people with English as another language may find contractions difficult to understand.

Avoid less common coloquial contractions, like you'd.

Always consider the context:

* Avoid contractions in situations where there is no room for misunderstanding, such as forms or other situations where users are being asked to submit information.
* Consider also the number of contractions in a single sentence. Avoid sentences with consecutive or multiple contractions.

Contractions that include the first and last letter of a word don’t need a full stop.

For example

Ms, Pty Ltd, Dr

Please also see

Apostrophes

**Comment by fearlesssteven** [comment]
I still think Ms, Pty Ltd., and Dr are all abbreviations. 

Supported by https://en.wikipedia.org/wiki/Abbreviation

Rather than just raise problems I'll draft something a bit later and get back to y'all.

**Comment by joolswood** [comment]
I'm inclined to agree @fearlesssteven do you want to do an edit to the current Abbreviations entry?

**Comment by joolswood** [comment]
Hey @michaelhugill we removed the forms bit originally as there were examples of forms where we did use contractions for good reason; but I can see value in providing it like this, in terms of a warning.

Not sure about the second dot point, do we have an examples of where this has been a problem? I was also thinking that sentences that had more than 1 contraction might invariably end up being longer than we would normally use? ie the rule around writing short sentences may help to avoid/"trump" this situation?

**Comment by michaelhugill** [comment]
@fearlesssteven I agree too.

@joolswood Second dot point = something a few of us discussed in Canberra the other day. I think it comes from the idea that a sentence filled with apostrophes (and other punctuation) might be hard to read for some people. Will leave with you.

**Comment by joolswood** [comment]
Related to PR 199
