### ISSUE TITLE
Not using the word 'topics'

### ISSUE THREAD

**Issue by michaelhugill** [AusDTO/gov-au-content-guide#124]
## What do you need?

We probably need a content style guide entry to instruct against using the word 'topic/s' and why – especially in navigational areas, and potentially in body text too.

What is the problem?

I've asked Donna to add more info to this ticket when she can. In the meantime...

The words 'topic' and 'topics' are problematic and could create user confusion between topic in the general sense and topic as a kind of system noun.

In general, we don't label a topic (system noun) as a 'topic'. We've also been avoiding referring to other topics.

## Which entry/section is this related to?

I'm not sure – it might need it's own entry.

## Good example

We've been experimenting with terms like 'Information and services', 'Related information', 'More information', 'You might also like/need' etc (but those ones may need further discussions too).

**Comment by maadonna** [comment]
The basic reason is that 'topic' is our jargon. For us a topic is a hierarchy of information pages on a single thing. The word is used differently in general use and by similar organisations like uk.gov (to them a topic is a page). However, it will be easy for us, and for authors in the future, to slip it into the interface. Users won't know what it relates to :) When we are tempted to use it in the interface, think about what we are trying to tell people - are we trying to differentiate between different types of resources (gov.au and external resources), label a set of tags on a news story, label a set of related links - then think of how better to help them understand what they are looking at.

**Comment by joolswood** [comment]
Come back to with Michael

**Comment by michaelhugill** [comment]
Hi @joolswood, do you need more from me? Does the above not cover it?

**Comment by joolswood** [comment]
@michaelhugill not necessarily; I was just assigning issues for discussion at the next CC to the people who created the ticket so they could talk to the item.

**Comment by michaelhugill** [comment]
@joolswood Sounds good. Let's discuss at next CC.

**Comment by joolswood** [comment]
We decided this is an internal content issue - not for content guide at the present.
