### ISSUE TITLE
Guidance on when to use brackets

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#125]
## What do you need?

Guidance on when to use brackets (especially in cases where commas are an option too). Asked by Matthew McCarthy.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/p.html#punctuation
http://content-style-guide.apps.staging.digital.gov.au/az-indexes/c.html#commas

**Comment by joolswood** [comment]
We should also do a related entry for 'parentheses'

**Comment by joolswood** [comment]
Libby to do some desktop research.

**Comment by libbyv** [comment]
AA to check how screen readers respond.
IE whether it's better to use brackets over a set of commas.
Possibly yes.

**Comment by AndrewArch** [comment]
Screen readers pause ever so slightly when they encounter a comma (like we do when we read aloud). However, they announce the opening and closing of brackets (and the type of bracket) when they encounter these - so a slight disruption to the reading flow like it is visually.  my take - use brackets sparingly.

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/47
