### ISSUE TITLE
Referring to legislation

### ISSUE THREAD

**Issue by lhowdin** [AusDTO/gov-au-content-guide#139]
When linking to legislation, use the bookmark tool in legislation.gov.au to ensure link is to the current version (unless of course you are referring to an historical version).

**Comment by joolswood** [comment]
Hey @lhowdin can you link to the tool please?

**Comment by joolswood** [comment]
Ah, just found it! Can I have a chat about how this might work?

**Comment by lhowdin** [comment]
To link to the latest legislation, select the bookmarkoption 'Go to latest', right click and copy link.  We might need some other advice about when and how to refer to legislation in general.  That is something that should probably be discussed with lawyers, maybe the Australian Government Solicitors would have something to say about it...but check they are not charging you before you get their help :) 
![image](https://cloud.githubusercontent.com/assets/13686451/17914730/df498252-69e7-11e6-9729-2ec268f04d6b.png)

**Comment by joolswood** [comment]
eg. https://www.legislation.gov.au/Latest/C2016C00763

**Comment by joolswood** [comment]
Cheers @lhowdin

**Comment by joolswood** [comment]
Add to guide, possibly `hyperlink` section.

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/34
