### ISSUE TITLE
Fractions guidance

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#145]
## What do you need?

Guidance on writing fractions. Andrew confirms decimals are preferable (0.5 1.5). Need to consider 2/3, 3/4 and so on.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/n.html#numbers

**Comment by joolswood** [comment]
Libby to talk to Andrew

**Comment by AndrewArch** [comment]
I'll take on to investigate screen reader issues (if any) with the various alteratives

**Comment by libbyv** [comment]
Suggestion: We agree decimals for simple fractions eg 2.5, 0.5 etc.

AA to investigate best approach for two-thirds versus 2/3 with screen readers.

**Comment by AndrewArch** [comment]
Suggestion is to use percentage (eg nn%) where ever appropriate. Response from an experienced JAWS user ...
```
Response in _italics_ for each point/question.

for one-half - 1/2 (one slash two) or 0.5 _JAWS states ‘one half’ with or without subscript activated or zero point five for the decimal example_
for one-third - 1/3 (is it pronounced 1 / 3 or one third?) - as a decimal it would be 0.3333 repeating so no good as a decimal _JAWS states ‘one slash three’_
some others - 3/4, 1/4, 1/5 etc. _JAWS states ‘three slash four’, ‘one slash four’ and ‘one slash five’_
what is the safest way to represent these to be sure they are understood? _I would use whole words to describe the fraction i.e. one half, three quarters, one fifth etc. or, depending on context ‘up to 1/3  of respondents stated…..’ use the percentage 33%_
 
This works with 'say all’ or word by word.  I’m using JAWS 17 with intermediate level of verbosity and some punctuation.
```

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/48
