### ISSUE TITLE
Provide guidance on writing headings to be contextually meaningful when read stand-alone

### ISSUE THREAD

**Issue by klepas** [AusDTO/gov-au-content-guide#146]
This card comes from the user a11y testing gov.au and uikit performed with Scott Grimley.

The concerns are around multiple headings (esp. of the same hierarchy type) on a page, which we found to be confusing to screen reader users to navigate through: eg “Get more help” 5x a page is crap; “Get more help with X” is useful.

In general this also relates to guidance around writing content while keeping the logical flow of the DOM (document object model; the logical HTML markup tree) in mind — eg. “Follow these steps” as a page abstract, which is followed by a series of Index/TOC links for the page can be confusing.

**Comment by joolswood** [comment]
Assign to Michael - will catch up with him

**Comment by joolswood** [comment]
http://content-style-guide.apps.staging.digital.gov.au/az-indexes/h.html#headings-and-subheadings
http://content-style-guide.apps.staging.digital.gov.au/az-indexes/s.html#structuring-a-page
Add "Being able to understand the page content from the headings alone"

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/54
