### ISSUE TITLE
Commas in numbers

### ISSUE THREAD

**Issue by matthewmccarthyDTO** [AusDTO/gov-au-content-guide#147]
Use the GitHub title line for your issue, then delete these lines.

Please log a separate GitHub issue for each comment.
## What do you need?

What is the problem?
## Which entry/section is this related to?

For example: Hyperlinks
## Good example

Have you seen style content elsewhere we should look at?

**Comment by joolswood** [comment]
Ask Andrew Arch about screen reader usage.

**Comment by joolswood** [comment]
@joolswood also to talk to UI-KIT team about rendering.

**Comment by libbyv** [comment]
Agree that up to 9999 no commas and then commas used ie 10,000 - Andrew to double confirm.

**Comment by AndrewArch** [comment]
Has this number pattern been usability/readability tested? I'm concerned that not including a comma in numbers with 4 digits makes them harder to  understand - especially for people with reading and learning difficulties (ie familiarity helps recognition helps understanding)

**Comment by joolswood** [comment]
Happy to reopen this ticket if needs be @AndrewArch @libbyv

**Comment by AndrewArch** [comment]
As I recall I checked for screen readers - not a problem for them. I obviously didn't think more broadly :(

**Comment by libbyv** [comment]
Agree it would be good to check that Andrew. Thanks

**Comment by AndrewArch** [comment]
breaks for long numbers - `Similarly, it is easier to recall 3 digits over 4, as both these graphs demonstrate` - http://ux.stackexchange.com/questions/74851/ideal-breaks-for-long-numbers#answer-75318

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/38
