### ISSUE TITLE
Paragraph breaks

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#149]
## What do you need?

What I’m trying to suggest is a move away from talking about paragraphs and instead talking about 'paragraph breaks’.

This is based on my experiences talking about this with writers, who get inevitably get confused and start writing bad sentences because they’re trying to fit some paragraph rule.

What I’m really talking about is presenting text, rather than constructing text.

The websites I see these days that are handling text really cleanly and neatly are putting in a break every 1 or 2 sentences. A paragraph construction rule doesn’t apply because much because nothing’s getting lost inside a block of text any more.

All the text then becomes readable and scannable.

Generally, the content on the [Structure your page for readability](http://content-style-guide.apps.staging.digital.gov.au/writing-for-the-web/3-structure-your-page-for-readability.html) could also be made plainer.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/p.html#paragraphs
http://content-style-guide.apps.staging.digital.gov.au/writing-for-the-web/3-structure-your-page-for-readability.html

**Comment by joolswood** [comment]
As discussed, please can someone add the wording discussed in the Content Clinic.

**Comment by joolswood** [comment]
Hi @michaelhugill please can you add some text around this.

**Comment by AndrewArch** [comment]
Beg to differ on the readability/scanability aspect - don't artificially insert 'paragraph breaks' every few sentences, if I understood @joolswood correctly. Keep the idea within a single paragraph - rewrite the paragraph if it seems too long!

**Comment by joolswood** [comment]
Review text with these changes:
- mobile first
- 1-2 sentences

**Comment by joolswood** [comment]
From @libbyv:
```
Short paragraphs make it easier to read text on mobile screens.

Try limiting paragraphs to 1 to 2 sentences. Or break up the text into bullet points to improve readability.
```

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/36
