### ISSUE TITLE
Content types

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#154]
## What do you need?

Discussion in the Content Clinic about how we are working with / planning for content types, and how the Content Guide can support this work.

It would be great if you could lead this @lhowdin 
## Which entry/section is this related to?

Nil so far.
## Good example

https://www.gov.uk/guidance/content-design/content-types

**Comment by maadonna** [comment]
I'll be fairly heavily involved in this. Defining what content types we have and how we use them is pretty core IA work :)

**Comment by joolswood** [comment]
Of course @maadonna !

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/62
