### ISSUE TITLE
Remove www from links

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#162]
## What do you need?

Decision on whether we can advise to remove the `www` from URLs yet.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/h.html#hyperlinks
## Good example

https://pages.18f.gov/content-guide/urls-and-filenames/

**Comment by joolswood** [comment]
Clinic agreed to drop the `www`

**Comment by joolswood** [comment]
Comments from @klepas "I think it’s OK to advise dropping it, *provided* (as you noted) they ensure the shorthand with the prefix omitted works. DNS, URL/URI changes can always happen, and something we can’t control."

**Comment by klepas** [comment]
Just adding: some sites aren’t set up to route without `www` — this can be a constraint, or just a lack of config.

**Comment by joolswood** [comment]
@klepas better?

**Comment by klepas** [comment]
@joolswood I added a comment based on the edits you made in the PR.

**Comment by joolswood** [comment]
@klepas did I miss a comment? I can't see anything. Or do you think it needs to be more explicit about the why?

**Comment by klepas** [comment]
@joolswood Ah, my bad — I’m confused as to how GH reviews works — you have to add your note to a line, and then click ‘Submit review’ in the top right of the files changed view tab it seems.

Should be there now on the PR: https://github.com/AusDTO/gov-au-content-guide/pull/204#pullrequestreview-7572216

**Comment by joolswood** [comment]
Just added a commit for this @klepas https://github.com/AusDTO/gov-au-content-guide/pull/204/commits/6c3721eacfb7125f3e38e87bfff12d0e1d6cf5fa But I'm still a bit concerned though that the difference between a redirect and a routed URL is not clear. It's not 100% clear to me. How would an average user work out which one a site used (don't say just look at the URL :p)

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/22
