### ISSUE TITLE
Provide guidance on writing tables

### ISSUE THREAD

**Issue by klepas** [AusDTO/gov-au-content-guide#167]
The current draft of the design guide has some guidance on tables, but more from a technical perspective: https://gov-au-ui-kit.apps.staging.digital.gov.au/section-tables.html

It would be great to see some guidance on writing tabular content (when, what to do; what not to do, etc.).

**Comment by joolswood** [comment]
https://gov-au-ui-kit.apps.staging.digital.gov.au/section-tables.html#guide-tables-3-accessibility

**Comment by joolswood** [comment]
Libby has started a doc - Tables_content for new entryT

**Comment by AndrewArch** [comment]
one consideration is that 'complex' tables or large tables should be broken down to simpler/small tables where  ever possible to aid cognitive processing generally.

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/53
