### ISSUE TITLE
Resources section

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#175]
## What do you need?

Decision on if we she should add a tools/resources page or section.

I'm not a big fan of lists of resources as they don't give context as well as crafted inline links.

Lots of links in the parked doc we can use.

**Comment by maadonna** [comment]
My opinion is that these are lazy IA. people should be able to find what they need via the topic of interest, not from a 'resources' list :)

**Comment by joolswood** [comment]
Content Clinic: dedicated section probably not needed for the content guide; however some guidance on using lists of resources may be valuable.

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/42
