### ISSUE TITLE
Consistent style for opening hours and AEST etc

### ISSUE THREAD

**Issue by nigelbartlett** [AusDTO/gov-au-content-guide#178]
Consistent style for opening hours and AEST etc
## What do you need?
1. Can we have a consistent style for the ordering of opening/operating hours for phone lines, organisations and so on. 2. Can we just use AEST (etc) instead of spelling it out the first time.

What is the problem?
1. In Agency/Topic we run opening/operating hours as follows: 

[Organisation name]
02 6271 1000
9am to 5pm Australian Eastern Standard Time (AEST)
Monday to Friday excluding ACT public holidays

But in Transition we run them like this:
[Organisation name]
Monday to Friday 9am to 5pm AEST
Call: 8266 5260 or 1300 885 886
1. Do we need to spell out AEST (etc) when we're dealing with micro-copy?
## Which entry/section is this related to?

Dates & Time Periods (but should also be in Phone Numbers and also Times)

**Comment by joolswood** [comment]
Relates to #193

**Comment by joolswood** [comment]
[Organisation name]
Monday to Friday
9am to 5pm AEST (Australian Eastern Standard Time)
03 8266 5260 or 1300 885 886

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/40
