### ISSUE TITLE
Inline glossary for editing tool

### ISSUE THREAD

**Issue by michaelhugill** [AusDTO/gov-au-content-guide#179]
## What do you need?

What is the problem? Long story short: there are government terms that can't be rewritten (eg portflio, parliament, senate etc) but have low readability. 

We can't simply add an explanation every time these words appear, so an inline glossary (perhaps a link or 'hover over' functionality) would help users to understand the term.

This is NOT about govspeak, eg ensure, implement, drive etc. This is usually about government nouns.
## Which entry/section is this related to?

To be determined.
## Good example

Ask @coderdan for examples and ideas. Please also check with Dan about how this can be ticketed in the platform/sites github.

**Comment by joolswood** [comment]
Being tracked in JIRA too: `GOVAU-484`

**Comment by joolswood** [comment]
Linked to #153

**Comment by joolswood** [comment]
Have commenced the list. We might make this an activity as part of a future content clinic.

**Comment by joolswood** [comment]
Will move the list to a yaml file in `/data/` folder of repo.

**Comment by joolswood** [comment]
Need to return to this with relevant people - check needs are still the same. Also cloud.gov.au are interested in something similar https://ausdto.slack.com/archives/content-design/p1475232268000064

**Comment by joolswood** [comment]
I've split the work involved. This ticket is about the technical implementation of the list of words say for instance as part of the editing tool. #153 is about the writing of the list of words (non technical in the main).

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/45
