### ISSUE TITLE
Second level bullet points

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#180]
## What do you need?

Guidance on using (or not using) second level bullet points.
## Which entry/section is this related to?

http://content-style-guide.apps.staging.digital.gov.au/az-indexes/b.html#bullet-point-lists
## Good example

https://www.gov.uk/guidance/style-guide/a-to-z-of-gov-uk-style#bullet-points-steps
https://pages.18f.gov/content-guide/punctuation/

**Comment by joolswood** [comment]
Add content to avoid 2nd level bullets and add example showing how to re-work (see Google Group).

**Comment by AndrewArch** [comment]
what's the rationale for discouraging 2 levels of bullets?

**Comment by joolswood** [comment]
@AndrewArch I'd suggest it's to cap the complexity of sentences. Once you add in the second level you're increasing the cognitive load in scanning the sentence (needing to remember 2 "spines"* instead of 1). @fearlesssteven ?

*`spine` probably isn't the right word - what do you call the bit before the colon in a list?

**Comment by joolswood** [comment]
You can review changes here: http://content-guide-180-bulletpoints.apps.staging.digital.gov.au/az-indexes/b.html#bullet-point-lists

**Comment by joolswood** [comment]
I feel like I need some more content designer input on this so am knocking this back to Content Clinic.

**Comment by joolswood** [comment]
Content Clinic happy to publish as is

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/23
