### ISSUE TITLE
Expand on the use of italics

### ISSUE THREAD

**Issue by matthewmccarthyDTO** [AusDTO/gov-au-content-guide#181]
## What do you need?

Expand content guide to include italics use in Annual Reports

What is the problem?

Not a current rule around how Acts are italicised 
## Which entry/section is this related to?

Italics
## Good example

Have you seen style content elsewhere we should look at?

**Comment by joolswood** [comment]
To discuss with @AndrewArch

**Comment by AndrewArch** [comment]
While italicised text is harder to read (especially for many people with dyslexia) that doesn't mean it should _never_ be used -  just use it (very) sparingly. 
Thus, the occasional use of italicised text for Acts of Parliament and for Latin names is acceptable. However, do not draw attention to other blocks of text or phrases with emphasised/italicised text.

The WCAG 2.0 Guideline 3.1: 'Make text content readable and understandable' does not  dis-allow italics either, but advises we try 'Avoiding chunks of italic text' 
(https://www.w3.org/TR/UNDERSTANDING-WCAG20/meaning.html)

**Comment by joolswood** [comment]
Content Clinic: link Italics guidance to bold and titles (ie keep the same approach)

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/34
