### ISSUE TITLE
What is the preferred way to refer to text/SMS messages?

### ISSUE THREAD

**Issue by NoniH** [AusDTO/gov-au-content-guide#189]
## What do you need?

Guidance on preferred terminology (or when to use what) for texts or SMS messages. 

Context: when logging in someone my choose to receive a code via SMS/text. 
## Which entry/section is this related to?

Mobile?

**Comment by joolswood** [comment]
Content Clinic rec: "text message"

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/35
