### ISSUE TITLE
Referring to all 3 levels of government together

### ISSUE THREAD

**Issue by NoniH** [AusDTO/gov-au-content-guide#190]
## What do you need?

How do we refer to all 3 levels of government together? E.g. Federal/commonwealth, state and territory and local government. 

For example:
This tool cal be used when applying for all Australian government services (federal, state and territory and local).

Things to consider: How will this make use of the government naming conventions currently in the guide?
## Which entry/section is this related to?

Government
## Good example

Common terminology in schools is: Federal, state and local. 
http://www.peo.gov.au/multimedia/videos/snapshots-three-levels-of-government.html

**Comment by joolswood** [comment]
We did a survey to focus on what we call the national government (Australian Government) but not all 3 levels.

Possibly the results may still help with the naming of the others.

**Comment by joolswood** [comment]
https://leisareichelt.typeform.com/report/geoaK5/Y41X

**Comment by NoniH** [comment]
Thanks for the survey results Jools. It would be good to make a call on this in the next clinic.

**Comment by joolswood** [comment]
Hi @NoniH we discussed this in Content Clinic and we we're hoping you can take a look at some other style guides and see how they've done it?

**Comment by NoniH** [comment]
I can't seem to find any official style guides that refer to using the three levels of government together. Do you know of any?

References I can find:
**Federal, state and local** (commonly used both in Australia and internationally)

**Federal (or national) Parliament, in Canberra. State/territory parliaments, in each state/territory capital city. Local councils (also called shires or municipalities), across the nation.**
[http://www.peo.gov.au/learning/fact-sheets/three-levels-of-law-making.html ]
**Federal, state or territory and local.**
[http://education.aec.gov.au/teacher-resources/three-levels.html]
**Local government or councils (also called shires or municipalities). State or territory governments. Federal government.**
[http://www.aec.gov.au/indigenous/files/iepp-factsheet-three-levels.pdf]

It seems pretty clear that:

- **federal** is the most common way to refer to the Australian Government.
- **local** is the most common reference for local municipalities, however it is often referred to as "local council" rather than "government". 
- there is difference for state/territory, State and Territory, or just state. 

Is there preference between the following?

1. federal, state/territory and local government
2. federal, state or territory and local government
3. federal and state/territory governments and local councils

Or any other suggestions?

**Comment by NoniH** [comment]
Wording on GOV.AU: [https://www.gov.au/about]
**the Australian Government and state, territory and local governments**

This does fit within the current style guide so is then perhaps preferable.

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/29
