### ISSUE TITLE
Time zones

### ISSUE THREAD

**Issue by fearlesssteven** [AusDTO/gov-au-content-guide#193]
## What do you need?

A new entry in the DTO Style Guide relating to time zones.

Suggest:

Time zones

Across Australia there are 3 time zones —plus daylight savings during summer months in some locations — with the acronyms AEST, AEDT, ACST and AWST. 

These acronyms are not always known intuitively. 

Avoid, where possible, by using the name of a key city instead. 

**For example**

Applications close 15 January 2017 at 6pm (Canberra).

Context often means you do not need to reference a time zone. 

What is the problem?

Missing entry
## Which entry/section is this related to?

For example: Time or _new entry_ Time zones
## Good example

Have you seen style content elsewhere we should look at?

I couldn't find anything on 18F.

**Comment by joolswood** [comment]
Content Clinic decision to continue including the acronyms.

**Comment by klepas** [comment]
I can see us wanting to provide some technical information here too (although possibly just a reference; we could provide more guidance on this in the Design Guide) — eg, see:

- http://www.brucelawson.co.uk/2012/best-of-time/
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/time

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/40
