### ISSUE TITLE
Contractions entry in Style Guide

### ISSUE THREAD

**Issue by michaelhugill** [AusDTO/gov-au-content-guide#194]
## What do you need?

I think we could consider an update to the Contractions entry in the Style Guide.

## What is the problem?

The way the entry is currently laid out opens it up to misinterpretation – it seems one person (not me!) may have interpreted the example box as telling authors to convert contractions back to two words.

Also, it may have drifted away a little from our mantra of helping authors how to use a thing more than teaching them what a thing is. 

## Which entry/section is this related to?

Contractions

## My suggestion

Here's a first go at a first edit:

Contractions

[Optional definition] When 2 adjacent words are contracted into 1, an apostrophe is used to show that letters have been left out.

Be aware that low-literacy users, or people from non-English speaking backgrounds may find contractions difficult to understand.

Always consider the context. Avoid contractions in situations where there is no room for misunderstanding. For example, in situations where users are being asked to submit information.

Consider also the number of contractions in a single sentence. For example, avoid sentences with consecutive or multiple contractions.

Contractions that include the first and last letter of a word don’t need a full stop. For example, Ms, Pty Ltd, Dr

Please also see
* Apostrophes

**Comment by joolswood** [comment]
Hi @michaelhugill see #123 - some draft wording discussed with @libbyv

**Comment by joolswood** [comment]
Closing this - please use #123 instead
