### ISSUE TITLE
Card sort exercise to inform Content Guide IA

### ISSUE THREAD

**Issue by joolswood** [AusDTO/gov-au-content-guide#196]
- [X] @joolswood to tweak cards in spreadsheet https://docs.google.com/spreadsheets/d/1i0lXqvZKbVauDqG5KwecBDPOwS6QoXFpojgkYOe3BeQ/edit#gid=0~~
- [X] @maadonna will set it up the exercise.
- [x] Confirm roles
- [x] Draft release email

**Comment by joolswood** [comment]
It's live!

**Comment by klepas** [comment]
Just looking for an update — can we close this card? :S

**Comment by maadonna** [comment]
I'm doing analysis of results now - let's close it when I finish that

**Comment by joolswood** [comment]
Card sort activity now completed! See results here: https://docs.google.com/spreadsheets/d/1i0lXqvZKbVauDqG5KwecBDPOwS6QoXFpojgkYOe3BeQ/edit#gid=372668572

**Comment by klepas** [comment]
@joolswood Could I ask you to give a brief summary on the results? :S

**Comment by joolswood** [comment]
@klepas certainly. I'm hoping to go into it in depth with Content Clinic in 2 weeks' time but I can talk you through it before then.

**Comment by klepas** [comment]
@joolswood Keen to timebox a summary run-through to like 10–15mins or something. Lemme know when works for you? Happy to wait until we catch up in-person next week. (:

**Comment by joolswood** [comment]
@klepas I'm happy to book in some time this arvo if the rest of the team are interested, otherwise have a chat Monday?
