### ISSUE TITLE
Guidance on language around accounts

### ISSUE THREAD

**Issue by AlzbetaT** [AusDTO/gov-au-content-guide#200]
Guidance on the approach and language around account:

**Sign in/Sign up vs Log in/Log out ?**

**Create an account/Register/Join ?**

While it seems to be a pretty even split with for/against for each... (to me) there is something about 'Log in' that doesn't feel like it accurately conveys the meaning of what the user is actually doing, like "Sign in"... "entering something vs noting something"?

**Comment by joolswood** [comment]
Content clinic - preference for `Sign in`, `Sign out` Registration requires more consideration.

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/33
