### ISSUE TITLE
Make sure single quotation is not entered as an apostrophe (accessibility issues)

### ISSUE THREAD

**Issue by NoniH** [AusDTO/gov-au-content-guide#225]
When single quotation marks are entered as an apostrophe, Jaws screen reader doesn't recognise it as quotation. 

Suggestion: Add advice about how to create a single quotation mark rather than using apostrophes. 

Open quote = option-]
Close quote = option-shift-]

## What do you need?

What is the problem?

## Which entry/section is this related to?

For example: Hyperlinks

## Good example

Have you seen style content elsewhere we should look at?

**Comment by joolswood** [comment]
https://github.com/govau/content-guide/issues/117
